# Using V2 as advised here: https://github.com/docker/compose/issues/4513#issuecomment-368167466
version: "2.4"

services:
  app:
    build:
      context: .
    environment:
      FLASK_APP: ${FLASK_APP:-app}
      FLASK_DEBUG: ${FLASK_DEBUG:-0}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    container_name: 'log-my-time'
    image: 'log-my-time:latest'
    restart: always
    volumes:
      - './db:/home/app/log-my-time/db/'
    ports:
      - ${FLASK_PORT:-4000}:5000

  cache:
    image: redis:6-alpine
    restart: always
    container_name: 'log-my-time-cache'
    command: redis-server
    volumes:
      - './cache:/var/lib/redis'
    environment:
      - REDIS_REPLICATION_MODE=master
