# Overrides for development
# Used automatically unless the `-f` flag is passed
version: "2.4"

services:
    app:
        build:
            context: .
        mem_limit: ${MEM_LIMIT:-2147484000} # 2GiB
        cpus: ${CPU_LIMIT:-0}
        environment:
            FLASK_APP: ${FLASK_APP:-app}
            FLASK_DEBUG: ${FLASK_DEBUG:-1}
            LOG_LEVEL: ${LOG_LEVEL:-warning}
        volumes:
            - "./app:/home/app/log-my-time/app"
            - "./db:/home/app/log-my-time/db"
            - "./config:/home/app/log-my-time/config"
            - "./tests:/home/app/log-my-time/tests"
            - "./migrations:/home/app/log-my-time/migrations"
            - "./debug:/home/app/log-my-time/debug"

    # Container that is used for running tests
    test:
        container_name: "log-my-time-test"
        build:
            context: .
            args:
                - TEST_MODE=1
        command: tail -f /dev/null # This container does nothing, we leave it spinning then run the test running inside it
        mem_limit: ${MEM_LIMIT:-2147484000} # 2GiB
        cpus: ${CPU_LIMIT:-0}
        environment:
            FLASK_APP: ${FLASK_APP:-app}
            FLASK_DEBUG: 0
            LOG_LEVEL: ${LOG_LEVEL:-warning}
            TEST_MODE: "yes"
        volumes:
            - "./config:/home/app/log-my-time/config"
            - "./migrations:/home/app/log-my-time/migrations"
            - "./debug:/home/app/log-my-time/debug"

    cache:
        mem_limit: 2147484000 # 2 GiB
        cpus: 2
