# Overrides for development
# Used automatically unless the `-f` flag is passed
version: "2.4"

services:
  app:
    build:
      context: .
    environment:
      FLASK_APP: ${FLASK_APP:-app}
      FLASK_ENV: ${FLASK_ENV:-dev}
      FLASK_DEBUG: ${FLASK_DEBUG:-1}
      LOG_LEVEL: ${LOG_LEVEL:-warning}
    volumes:
      - './app:/home/app/time-tracker/app'
      - './config:/home/app/time-tracker/config'
      - './tests:/home/app/time-tracker/tests'
