[tool.djlint]
profile = "jinja"
ignore = "J004,J018,H006,T002,H021,H031"
max_line_length = 999
max_attribute_length = 999
blank_line_after_tag = "load,extends,include,csrf_token,endblock,endwith,endif,endmacro"

# This regex should match all custom-elements with up to 4 words
# This regex should match any number of words but it doesn't work: '\w+-\w+(\-\w+)+'
custom_html = '\w+-\w+,\w+-\w+-\w+,\w+-\w+-\w+-\w+'

preserve_blank_lines = true
preserve_leading_space = true
format_js = true
format_css = true

[tool.djlint.js]
indent_empty_lines = false
wrap_line_length = 120
brace_style = "preserve-inline"

[tool.ruff]
line-length = 120
ignore = [
    "E711", # Interferes with SQLAlchemy conditions
    "E712", # Interferes with SQLAlchemy conditions
    "E501", # Ruff handles line length, this rule just gets angry at long strings
]

[tool.pyright]
typeCheckingMode = "basic"
reportGeneralTypeIssues = "information"
reportOptionalMemberAccess = "information"
reportOptionalCall = "information"
reportPrivateImportUsage = "information"
