"""Add Break.user_id

Revision ID: 1743184516
Revises: 1733593456
Create Date: 2025-03-28 17:55:16.881867

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1743184516"
down_revision: Union[str, None] = "1733593456"
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("break", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))

    with op.batch_alter_table("break", schema=None) as batch_op:
        batch_op.execute("UPDATE break SET user_id = (SELECT user_id FROM time WHERE time.id = break.time_id)")
        batch_op.alter_column("user_id", nullable=False)
        batch_op.create_foreign_key("fk_break_user_id_user", "user", ["user_id"], ["id"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_break_user_id_user"), "break", type_="foreignkey")
    op.drop_column("break", "user_id")
    # ### end Alembic commands ###
